name: Actions for branch develop
run-name: performing develop checks and upload to internal testing
on:
  push:
    branches:
      - develop
jobs:
  uploadPlay:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'
      - name: store keystore
        env:
          KEY_STORE_CONTENT: ${{ secrets.KEY_STORE_CONTENT }}
        run: base64 -d <<< $KEY_STORE_CONTENT > app/elegoo-app-keystore
      - name: build
        env:
          ANDROID_PUBLISHER_CREDENTIALS: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          KEY_STORE_KEY_PASSWORD: ${{ secrets.KEY_STORE_KEY_PASSWORD }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        run: ./gradlew :app:publishReleaseBundle

          
